---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: GregsNewFeature

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: false

conditions:
  - allOf:
      - property:
          name: GregDelete
          operator: is-true
    flagValue: true
